#!/usr/bin/python

import os

ORIGINAL_PATH = "/contest-data/original/"
COMPRESSED_PATH = "/contest-data/compressed/"
DECOMPRESSED_PATH = "/contest-data/decompressed/"

prefixes = set([x.split(".")[0] for x in os.listdir(COMPRESSED_PATH) if "." in x])

for fn in prefixes:
	os.system("java -jar fqzip.jar decompress %s %s" % (COMPRESSED_PATH + fn, DECOMPRESSED_PATH + fn))

